# pylint: skip-file

from typing import Callable, Optional, Any, List

class ReplCommand:
    def __init__(self, *args: Any, **kwawgs: Any) -> None: ...

class ReplRunner:
    def __init__(self, *args: Any, **kwawgs: Any) -> None: ...
    def add_commands(self, *args: Any, **kwawgs: Any) -> None: ...
    def run(self) -> None: ...
